import type { InventoryItem } from '@/types/inventory';

export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: '1',
    title: 'Jordan Flight Origin 3',
    category: 'kicks',
    status: 'available',
    price: 85,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: '820245-106', size: 10.5, colorway: 'White/Black' },
  },
  {
    id: '2',
    title: 'Adidas Racer TR23',
    category: 'kicks',
    status: 'available',
    price: 55,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'IG7322', size: 10, colorway: 'Core Black' },
  },
  {
    id: '3',
    title: 'Adidas Astrastar',
    category: 'kicks',
    status: 'available',
    price: 70,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'IF5312', size: 10, colorway: 'Cloud White' },
  },
  {
    id: '4',
    title: 'Adidas Grand Court 2.0',
    category: 'kicks',
    status: 'available',
    price: 60,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'GW9195', size: 10, colorway: 'White/Green' },
  },
  {
    id: '5',
    title: 'Adidas Kaptir 4.0',
    category: 'kicks',
    status: 'available',
    price: 65,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'ID1150', size: 10, colorway: 'Black/White' },
  },
  {
    id: '6',
    title: 'Adidas Nora',
    category: 'skate',
    status: 'available',
    price: 75,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'HP6011', size: 9.5, colorway: 'Maroon' },
  },
  {
    id: '7',
    title: 'New Balance ABZORB 2000',
    category: 'kicks',
    status: 'available',
    price: 90,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: null, size: 9, colorway: 'Grey/White' },
  },
  {
    id: '8',
    title: 'Adidas Duramo SL 2 M',
    category: 'kicks',
    status: 'available',
    price: 45,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'GW8336', size: 10, colorway: 'Black' },
  },
  {
    id: '9',
    title: 'Adidas Treziod 2',
    category: 'kicks',
    status: 'available',
    price: 50,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { sku: 'GY0047', size: 10, colorway: 'Core Black' },
  },
  {
    id: '10',
    title: 'Don Frye – Fighter Gear Relic',
    category: 'fight',
    status: 'available',
    price: 120,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: '063/188', set_name: 'Fighter Gear Relics', autograph: false },
  },
  {
    id: '11',
    title: 'Nick Diaz – Prizm Parallel',
    category: 'fight',
    status: 'available',
    price: 200,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: '52/99', set_name: 'Prizm UFC', autograph: false, parallel: 'Prizm' },
  },
  {
    id: '12',
    title: 'Aljamain Sterling – Select Signatures',
    category: 'fight',
    status: 'available',
    price: 350,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: null, set_name: 'Select Signatures', autograph: true },
  },
  {
    id: '13',
    title: 'Cain Velasquez – Fight Mat Relic',
    category: 'fight',
    status: 'available',
    price: 180,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: null, set_name: 'Fight Mat Relics', autograph: false, parallel: 'Event Used' },
  },
  {
    id: '14',
    title: 'Petr Yan – Opti-Graphs Auto',
    category: 'fight',
    status: 'available',
    price: 280,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: null, set_name: 'Opti-Graphs', autograph: true },
  },
  {
    id: '15',
    title: 'Brian Ortega – Prizm Signatures',
    category: 'fight',
    status: 'available',
    price: 260,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: null, set_name: 'Prizm Signatures', autograph: true },
  },
  {
    id: '16',
    title: 'Nate Diaz – Black Parallel',
    category: 'fight',
    status: 'available',
    price: 320,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: null, set_name: 'Chronicles', autograph: false, parallel: 'Black' },
  },
  {
    id: '17',
    title: 'Don Frye – Octagon of Honor',
    category: 'fight',
    status: 'available',
    price: 150,
    image_url: null,
    ref_image_url: null,
    created_at: '2026-05-01T00:00:00Z',
    metadata: { serial: null, set_name: 'Octagon of Honor', autograph: false },
  },
];
